title: Tejas Polu
position: Undergraduate Student
affiliation: University of California, Santa Cruz
email: tpolu [at] ucsc [dot] edu

keywords: Tejas Polu, Personal Webpage, Aritificial Intelligence, Machine Learning, Computer Science, Research
description: Personal Webpage of Tejas Polu
canonical: tejaspolu.github.io

google_scholar: https://scholar.google.com/citations?user=ayi83jgAAAAJ&hl=en
github_link: https://github.com/tejaspolu
linkedin: https://www.linkedin.com/in/tejas-polu/

avatar: /assets/img/tejas.png
favicon: /assets/img/tejas.png
favicon_dark: /assets/img/tejas.png

markdown: kramdown
permalink: pretty

enable_footnote: false
auto_dark_mode: false
font: "Serif"

remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
